# Generated by Django 3.2.7 on 2022-05-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, max_length=128, verbose_name='اسلاگ بلاگ'),
            preserve_default=False,
        ),
    ]
