# Generated by Django 3.2.7 on 2021-10-12 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(choices=[(1, 'باغبانی'), (2, 'کشاورزی'), (3, 'فروش')], verbose_name='موضوع')),
                ('text', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
                ('status', models.IntegerField(choices=[(1, 'باز'), (2, 'در حال بررسی'), (3, 'پاسخ داده شده'), (4, 'بسته شده')], verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
    ]
