# Generated by Django 3.2.7 on 2021-10-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
    ]
