# Generated by Django 3.2.7 on 2021-10-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticketcomment_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-updated_at'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['-updated_at'], 'verbose_name': 'جواب تیکت', 'verbose_name_plural': 'جواب های تیکت'},
        ),
    ]
