# Generated by Django 3.2.7 on 2021-10-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'در حال بررسی'), (2, 'ارسال شد'), (3, 'کنسل شد')], default=1, max_length=50, verbose_name='وضعیت'),
        ),
    ]
