# Generated by Django 3.2.7 on 2021-10-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(default=1, verbose_name='قیمت کامل'),
            preserve_default=False,
        ),
    ]
