# Generated by Django 3.2.7 on 2021-10-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'در حال بررسی'), (2, 'ارسال شد'), (3, 'کنسل شد')], default=1, verbose_name='وضعیت'),
        ),
    ]
