# Generated by Django 3.2.7 on 2021-09-23 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='نام')),
                ('slug', models.SlugField(max_length=128, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='product/brand', verbose_name='عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='نام')),
                ('slug', models.SlugField(max_length=128, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='product/category', verbose_name='عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='نام')),
                ('slug', models.SlugField(max_length=128, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='product/product', verbose_name='عکس محصول')),
                ('country', models.CharField(max_length=128, verbose_name='کشور')),
                ('weight', models.CharField(max_length=10, verbose_name='وزن')),
                ('volume', models.CharField(max_length=10, verbose_name='حجم')),
                ('formulation', models.CharField(max_length=128, verbose_name='فرمولاسیون')),
                ('packing', models.CharField(max_length=64, verbose_name='بسته بندی')),
                ('Elements', models.CharField(max_length=128, verbose_name='عناصر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('count', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('available', models.BooleanField(default=False, verbose_name='موجود')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
