# Generated by Django 3.2.7 on 2021-09-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/brand', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/category', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='زیر دسته'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Elements',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عناصر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='formulation',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='فرمولاسیون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/product', verbose_name='عکس محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='بسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='حجم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='وزن'),
        ),
    ]
