# Generated by Django 3.2.7 on 2021-09-28 22:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210928_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='low_description',
            field=models.TextField(default=0, verbose_name='توضیحات مختصر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='total_description',
            field=ckeditor.fields.RichTextField(default=0, verbose_name='توضیحات کامل'),
            preserve_default=False,
        ),
    ]
